import Foundation
import Combine

// MARK: - HypothesisOption

/// A selectable feedback option generated by the Agent for each prediction.
/// The user picks the option that best describes their situation; the Agent
/// uses it to perform an online parameter update.
struct HypothesisOption: Identifiable {
    let id = UUID()
    let emoji: String
    let label: String
    /// true  → user confirms Agent inference → positive reinforcement signal δ=+1
    /// false → user rejects Agent inference  → negative reinforcement signal δ=−1
    let isConfirmation: Bool
}

// MARK: - AgentPrediction

/// The complete output structure of one Agent prediction.
struct AgentPrediction {
    let state: MotorState
    /// Confidence in [0,1], computed as sigmoid(distance to decision boundary)
    let confidence: Double
    /// Technical explanation (with formula values, shown inside the Agent card)
    let explanation: String
    /// Clinical inference text (time- and medication-cycle-aware, shown in feedback card)
    let hypothesis: String
    /// User-selectable feedback options (up to 4)
    let options: [HypothesisOption]
    let sigma: Double
    let adaptiveThreshold: Double
}

// MARK: - PDMonitoringAgent

/// Adaptive PD motor-state monitoring Agent with reinforcement feedback.
///
/// ## Core formulas
/// ```
/// τ_adaptive = 0.65·τ_user + 0.35·τ_base
/// σ_w        = w₀·σ + w₁·(E/E_max)·σ·0.15 + w₂·|μ|·0.05
/// conf       = sigmoid(18 · min(|σ_w−τ|, |σ_w−2τ|))
/// τ_base    ← τ_base + α·δ·(σ_w − τ_base)          // gradient descent
/// w         ← w + α·δ·φ/‖φ‖  → normalised           // perceptron update
/// acc       ← acc·(1−α·β) + y·(α·β)                 // EMA, β=0.6
/// ```
@MainActor
final class PDMonitoringAgent: ObservableObject {

    // MARK: - AI ADAPTIVE LEARNING CORE (Mocked for Hackathon)

    /// τ_base: Agent's learned base threshold, initialised from PD literature resting-state level
    @Published private(set) var baseThreshold: Double = 0.118

    /// α: learning rate (typical range for Adam-style optimisers: [0.001, 0.1])
    let learningRate: Double = 0.05

    /// Feature weight vector w = [w_σ, w_energy, w_mean]
    private(set) var featureWeights: [Double] = [0.62, 0.28, 0.10]

    @Published private(set) var currentAccuracy: Double = 0.718
    @Published private(set) var feedbackCount: Int = 0
    private(set) var confirmedCorrectCount: Int = 0
    @Published private(set) var accuracyHistory: [Double] = [0.718]

    /// Snapshot of the most recent EMA update step values, used for UI formula rendering
    @Published private(set) var lastEmaSteps: EmaSteps? = nil

    struct EmaSteps {
        let accBefore: Double
        let decay:     Double   // 1 − α·β
        let y:         Double   // 0.0 or 1.0
        let emaRate:   Double   // α·β
        let accAfter:  Double
    }

    /// Most recent prediction cache (for feedback association and options list access in Views)
    @Published private(set) var lastPrediction: AgentPrediction? = nil

    private var lastWeightedSigma:    Double = 0.0
    private var lastAdaptiveThreshold: Double = 0.118

    // MARK: - Predict

    func predict(features: SensorFeatures, userThreshold: Double) -> AgentPrediction {

        // Adaptive threshold fusion
        let tau = 0.65 * userThreshold + 0.35 * baseThreshold

        // Weighted sigma
        let energyNorm = min(features.signalEnergy / 10.0, 1.0)
        let sigmaW = featureWeights[0] * features.sigma
                   + featureWeights[1] * energyNorm * features.sigma * 0.15
                   + featureWeights[2] * abs(features.mean) * 0.05

        // Classification
        let state: MotorState
        if sigmaW > tau * 2.0 { state = .tremor }
        else if sigmaW > tau  { state = .off    }
        else                  { state = .on     }

        // Confidence
        let d1 = abs(sigmaW - tau)
        let d2 = abs(sigmaW - tau * 2.0)
        let conf = sigmoid(min(d1, d2) * 18.0)

        lastWeightedSigma     = sigmaW
        lastAdaptiveThreshold = tau

        let explanation = buildExplanation(state: state, sigma: features.sigma,
                                           sigmaW: sigmaW, tau: tau, conf: conf)
        let (hypothesis, options) = buildHypothesis(state: state, sigma: features.sigma,
                                                    sigmaW: sigmaW, tau: tau)

        let prediction = AgentPrediction(
            state: state, confidence: conf,
            explanation: explanation, hypothesis: hypothesis, options: options,
            sigma: features.sigma, adaptiveThreshold: tau
        )
        lastPrediction = prediction
        return prediction
    }

    // MARK: - ADAPTIVE LEARNING CORE — feedback-driven online parameter update

    /// Receives the user-selected feedback option and executes one step of online gradient descent.
    ///
    /// **Step 1 — threshold gradient update:**
    /// ```
    /// δ = isConfirmation ? +1 : −1
    /// ∂L/∂τ ≈ −δ · (σ_w − τ_base)
    /// τ_base ← τ_base + α · δ · (σ_w − τ_base)
    /// ```
    /// **Step 2 — feature weight update (perceptron rule):**
    /// ```
    /// w ← w + α · δ · φ/‖φ‖  → normalised
    /// ```
    /// **Step 3 — accuracy EMA:**
    /// ```
    /// acc ← acc · (1−α·β) + y · (α·β),  β=0.6
    /// ```
    func adaptModel(basedOn feedback: Bool) {
        feedbackCount += 1
        if feedback { confirmedCorrectCount += 1 }

        let delta: Double = feedback ? 1.0 : -1.0

        // Step 1: threshold gradient update
        let gradTau = -delta * (lastWeightedSigma - baseThreshold)
        baseThreshold -= learningRate * gradTau
        baseThreshold = max(0.02, min(0.45, baseThreshold))

        // Step 2: feature weight update
        let phi: [Double] = [lastWeightedSigma, 0.10, 0.05]
        let phiNorm = sqrt(phi.reduce(0.0) { $0 + $1 * $1 })
        for i in featureWeights.indices {
            featureWeights[i] += learningRate * delta * (phi[i] / max(phiNorm, 1e-8))
        }
        let wSum = featureWeights.reduce(0.0) { $0 + max(0.0, $1) }
        if wSum > 1e-8 { featureWeights = featureWeights.map { max(0.0, $0) / wSum } }

        // Step 3: accuracy EMA
        let y: Double  = feedback ? 1.0 : 0.0
        let emaRate    = learningRate * 0.6
        let accBefore  = currentAccuracy
        currentAccuracy = currentAccuracy * (1.0 - emaRate) + y * emaRate
        currentAccuracy = max(0.0, min(1.0, currentAccuracy))

        lastEmaSteps = EmaSteps(accBefore: accBefore, decay: 1.0 - emaRate,
                                y: y, emaRate: emaRate, accAfter: currentAccuracy)
        accuracyHistory.append(currentAccuracy)
        if accuracyHistory.count > 20 { accuracyHistory.removeFirst() }
    }

    // MARK: - Hypothesis Generation — time- and medication-cycle-aware clinical inference

    /// Generates a clinically meaningful hypothesis text and feedback options based on
    /// the current time, motor state, and sigma value.
    ///
    /// Medication cycle model (typical three-dose levodopa regimen):
    /// - Morning dose:  ~07:30, effect duration 4–5h
    /// - Midday dose:   ~13:30, effect duration 4–5h
    /// - Evening dose:  ~19:00, effect duration 4–5h
    ///
    /// Each time window uses distinct inference logic and options.
    private func buildHypothesis(
        state: MotorState, sigma: Double, sigmaW: Double, tau: Double
    ) -> (String, [HypothesisOption]) {

        let now    = Date()
        let cal    = Calendar.current
        let hour   = cal.component(.hour, from: now)
        let minute = cal.component(.minute, from: now)
        let h      = Double(hour) + Double(minute) / 60.0
        let tStr   = String(format: "%02d:%02d", hour, minute)
        let sStr   = String(format: "%.3f", sigma)
        let tauStr = String(format: "%.3f", tau)

        // Time window definitions (based on typical three-dose levodopa schedule)
        let preMorning  = h >= 6.0  && h < 8.0    // 06:00–08:00 before morning dose
        let postMorning = h >= 8.0  && h < 12.0   // 08:00–12:00 morning effect period
        let preNoon     = h >= 12.0 && h < 14.5   // 12:00–14:30 before midday dose
        let postNoon    = h >= 14.5 && h < 18.0   // 14:30–18:00 midday effect period
        let preEvening  = h >= 18.0 && h < 20.5   // 18:00–20:30 before evening dose
        let postEvening = h >= 20.5 && h < 24.0   // 20:30–24:00 evening effect period
        let isNight     = h < 6.0                  // 00:00–06:00 nighttime

        switch state {

        // ── TREMOR ──────────────────────────────────────────────────
        case .tremor:
            if preMorning {
                return (
                    "Tremor amplitude (σ=\(sStr)) is significantly above your personal threshold (τ=\(tauStr)), ratio \(String(format:"%.1f",sigmaW/tau))x.\n\nCurrent time is \(tStr), just before the typical morning dose (~07:30). This is consistent with Morning Wearing-off — overnight, levodopa plasma levels drop to trough, causing increased morning tremor.\n\nAgent inference: morning dose likely not yet taken, or last evening dose was earlier than usual.",
                    [
                        HypothesisOption(emoji: "", label: "Morning dose not yet taken", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Last night's dose was earlier than usual", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Already took medication", isConfirmation: false),
                        HypothesisOption(emoji: "", label: "Just finished exercise", isConfirmation: false),
                    ]
                )
            } else if preNoon {
                let hoursAgo = String(format: "%.1f", h - 7.5)
                return (
                    "Current σ=\(sStr) exceeds 2τ — significant tremor detected.\n\nCurrent time is \(tStr), approximately \(hoursAgo) hours since last dose (~07:30). Levodopa half-life is ~1.5h, with typical effect lasting 4–5h. You may be entering an End-of-dose Wearing-off window.\n\nAgent inference: morning dose effect waning, midday dose not yet taken.",
                    [
                        HypothesisOption(emoji: "", label: "Medication effect feels like it's wearing off", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Midday dose not yet taken", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Feeling stressed or anxious", isConfirmation: false),
                        HypothesisOption(emoji: "", label: "Description does not match my state", isConfirmation: false),
                    ]
                )
            } else if preEvening {
                let hoursAgo = String(format: "%.1f", h - 13.5)
                return (
                    "Current σ=\(sStr) — increased tremor detected.\n\nCurrent time is \(tStr), approximately \(hoursAgo) hours since midday dose. The medication curve is approaching its trough. This is a typical afternoon Motor Fluctuation pattern.\n\nAgent inference: in a symptom trough before the evening dose.",
                    [
                        HypothesisOption(emoji: "", label: "Felt unwell all afternoon", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Evening dose not yet taken", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Poor sleep last night", isConfirmation: false),
                        HypothesisOption(emoji: "", label: "Feeling better than described", isConfirmation: false),
                    ]
                )
            } else {
                return (
                    "Atypical tremor pattern detected (σ=\(sStr), time \(tStr)) — outside the usual wearing-off window.\n\nPossible triggers: (1) muscle fatigue from recent exercise, (2) stress or emotional disturbance, (3) poor sleep, (4) excess caffeine intake.\n\nAgent inference: external factors may be amplifying the tremor signal.",
                    [
                        HypothesisOption(emoji: "", label: "Just did intense exercise", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Feeling stressed or anxious", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Poor sleep last night", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Cause unknown", isConfirmation: false),
                    ]
                )
            }

        // ── OFF ─────────────────────────────────────────────────────
        case .off:
            if postMorning || postNoon || postEvening {
                let medTime = postMorning ? "07:30" : (postNoon ? "13:30" : "19:00")
                return (
                    "Current σ=\(sStr) is between τ and 2τ — mild motor limitation detected.\n\nCurrent time is \(tStr), in the transition period after the \(medTime) dose. Levodopa typically takes 30–60 minutes to take effect.\n\nAgent inference: medication taken recently, ON state still building up.",
                    [
                        HypothesisOption(emoji: "", label: "Just took medication, waiting for effect", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Took medication with food — slower onset", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Feeling not as bad as described", isConfirmation: false),
                        HypothesisOption(emoji: "", label: "Description does not match my state", isConfirmation: false),
                    ]
                )
            } else {
                return (
                    "σ=\(sStr) is in a mild fluctuation range — slight motor limitation present.\n\nAgent inference: currently in an OFF/ON transition. Consider logging medication timing to help your doctor adjust the schedule.",
                    [
                        HypothesisOption(emoji: "", label: "Feeling mildly fatigued", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Just took medication", isConfirmation: false),
                        HypothesisOption(emoji: "", label: "Feeling fine", isConfirmation: false),
                    ]
                )
            }

        // ── ON ──────────────────────────────────────────────────────
        case .on:
            if postMorning || postNoon || postEvening {
                let medTime = postMorning ? "07:30" : (postNoon ? "13:30" : "19:00")
                return (
                    "Current σ=\(sStr) is below threshold (τ=\(tauStr)) — motor function is good.\n\nCurrent time is \(tStr), approximately \(String(format:"%.0f",abs(h-(postMorning ? 7.5:postNoon ? 13.5:19.0))*60)) minutes after the \(medTime) dose. This matches the typical levodopa ON peak — plasma levels at peak, tremor well controlled.\n\nAgent inference: currently in the optimal medication window.",
                    [
                        HypothesisOption(emoji: "", label: "Yes, feeling good", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Just took medication", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Not feeling as good as described", isConfirmation: false),
                    ]
                )
            } else if isNight {
                return (
                    "σ=\(sStr) shows stable motor state — normal nighttime data.\n\nCurrent time is \(tStr). Low tremor amplitude at night is typically associated with sleep or physical rest.\n\nSuggestion: if you just woke up, this is a good moment to log any nighttime symptoms.",
                    [
                        HypothesisOption(emoji: "", label: "Just woke up", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Nighttime symptoms are generally low", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Other", isConfirmation: false),
                    ]
                )
            } else {
                return (
                    "σ=\(sStr) is below threshold (τ=\(tauStr)) — no significant tremor or motor limitation detected.\n\nAgent inference: motor state is currently good. Continue normal activities and run another assessment whenever your state changes.",
                    [
                        HypothesisOption(emoji: "", label: "Feeling good", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Medication is working well", isConfirmation: true),
                        HypothesisOption(emoji: "", label: "Not feeling as good as described", isConfirmation: false),
                    ]
                )
            }

        case .unknown:
            return (
                "Insufficient data — Agent cannot generate a reliable inference. Please run another assessment.",
                [HypothesisOption(emoji: "", label: "Run again", isConfirmation: false)]
            )
        }
    }

    // MARK: - Helpers

    private func sigmoid(_ x: Double) -> Double { 1.0 / (1.0 + exp(-x)) }

    private func buildExplanation(
        state: MotorState, sigma: Double, sigmaW: Double, tau: Double, conf: Double
    ) -> String {
        let confPct  = Int(conf * 100)
        let ratio    = String(format: "%.2f", sigmaW / max(tau, 1e-6))
        let sigmaStr = String(format: "%.4f", sigma)
        let tauStr   = String(format: "%.4f", tau)
        switch state {
        case .on:
            return "σ=\(sigmaStr), τ_a=\(tauStr), ratio \(ratio) < 1.0 → ON. Confidence \(confPct)%."
        case .off:
            return "σ=\(sigmaStr), τ_a=\(tauStr), ratio \(ratio) ∈ [1,2) → OFF. Confidence \(confPct)%."
        case .tremor:
            return "σ=\(sigmaStr), τ_a=\(tauStr), ratio \(ratio) ≥ 2.0 → Tremor. Confidence \(confPct)%."
        case .unknown:
            return "Insufficient features (σ=\(sigmaStr)), confidence \(confPct)%."
        }
    }
}
